services:
  frontend:
    build: ./frontends
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontends:/app
      - /app/node_modules
    command: npm run dev  

  backend:
    build: ./backend
    command: bundle exec rails server -b 0.0.0.0 -p 3001
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: nti
      DATABASE_PASSWORD: 123
      DATABASE_NAME: backend_development
      RAILS_ENV: development
    volumes:
      - "./backend:/rails"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nti
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: backend_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test:
    build:
      context: ./backend
    command: bundle exec rspec
    environment:
      DATABASE_HOST: db
      DATABASE_USER: nti
      DATABASE_PASSWORD: 123
      DATABASE_NAME: backend_test
      RAILS_ENV: test
    volumes:
      - ./backend:/rails
    depends_on:
      - db

volumes:
  db_data: